[toolchain]
anchor_version = "1.0.0"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
security_tokens_manager = "5LrL1ep4NtbXoKz2QwBEBYp5DWEJeLx9hkYN8jiBH9k9"
transfer_hook = "EAGPJU5T8nEu5mfBFE4TTmtXZtFPhmPBSLsPrNDDhT2j"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
